# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bea236a658414e68bb603ef6db39f632b8462f3296256befe0f867ccb620e90c807a3a965733c5aff483712adc4021c0b1875e98d706c51f4565f413275b517e

test:
  secret_key_base: 6a26360942e906dd53314b6ce054845d4389bc32278469f624115e23825c43578a6927738b02164940f51d8e565d991ce219ff073c67eb42bd11f35389fb873d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
